
doorFixer:
  enabled: true # true or false

boatFixer:
  enabled: true # true or false

blocksForCancel:
  - NOTEBLOCK
  - COMMAND_BLOCK

messageOnCancel:
  enabled: true # true or false
  message: "#F2E9E4> #F28135Блок временно отлючён на сервере."
  #%block% Cancel block

mudBlock:
  effectLevel: 2
  blockList:
    - DIRT
    - SAND

blockHardness:
  blackstone:
    instruments:
      wooden_pickaxe:
        time: 1000
      stone_pickaxe:
        time: 170
      golden_pickaxe:
        time: 50
      iron_pickaxe:
        time: 100
      diamond_pickaxe:
        time: 50
      netherite_pickaxe:
        time: 25
    defaultTime: 1000000

dropEvent:
  enabled: true
  splitMultiplier: 2
  maxMinusValue: 10
  minMinusValue: 0
  items:
    - WHEAT_SEEDS
    - PUMPKIN_SEEDS
    - MELON_SEEDS
    - BEETROOT_SEEDS





